### ISSUE TITLE
Environment variables are persisted between runs

### ISSUE THREAD

**Issue by Yantrio** [ServiceStack/Gistlyn#3]
If you enter code like so
```
using System;

Console.WriteLine(int.Parse(Environment.GetEnvironmentVariable("PORT") ?? "4433"));
```
output will be 4433
if you then make another script like so

```
Environment.SetEnvironmentVariable("PORT", "444");
```

The environment variable is persisted  between runs, and the original script will always return 444

**Comment by mythz** [comment]
We can't exactly change that, the .NET API changes the Environment Variable, the only way to revert it is to reset the VM. But I've added `SetEnvironmentVariable()` to the set of [illegal tokens in this commit](https://github.com/ServiceStack/Gistlyn/commit/d38948587a9a07a1f701d307609947b94d94ab28).
