### ISSUE TITLE
NuGet import with newer PackageReference format

### ISSUE THREAD

**Issue by lionelhorn** [ServiceStack/Gistlyn#8]
Hello :)

Thanks and foremost, thanks for your work on ServiceStack 👍 

I was trying to import https://www.nuget.org/packages/Manatee.Json/ as a nuget package to a gist to send a bug repro gist to it's dev.

The format used in recent .net core csproj files differ from the package.json one you seem to use on Gistlyn.
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

Is it possible to add something like below to add this package as a nuget import?
```
<PackageReference Include="Manatee.Json" Version="12.0.3" /> 
```` 

From what I could gather, packages.json is an older format from previous nuget versions?
> (https://docs.microsoft.com/en-us/nuget/archive/project-json)
> > NuGet 3.x+
> > 
> > The project.json file maintains a list of packages used in a project, known as a package management format. It supersedes packages.config but is in turn superseded by PackageReference with NuGet 

- https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
- https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference

Thanks

**Comment by mythz** [comment]
No Gistlyn was developed using NuGet older v2 library to handle package importing, the library was rewritten in v3 which would require us to rewrite most of our API. Gistlyn is also a .NET Framework App that uses App Domains which can't be ported to .NET Core so it's basically limited to only running .NET Framework Apps that only reference NuGet v2 only features.

A complete rewrite, essentially a new project would be needed to run .NET Core Apps and the new MS Build project references. In which case your best bet is to use Microsoft's supported [Try .NET](https://github.com/dotnet/try) which lets you do something similar to Gistlyn.

**Comment by lionelhorn** [comment]
Thanks for the quick reply and the link.
